spring:
  profiles:
    active:
      - dev
---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/young?useUnicode=true&characterEncoding=utf8 #不需要\作为转移字符              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: dept-8081.com
    prefer-ip-address: true     #访问路径可以显示IP地址
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cqut.li.springcloud.entity  # 注意：对应实体类的路径
  configuration:
    #这个配置使全局的映射器启用或禁用缓存
    cache-enabled: true
    #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #配置默认的执行器。SIMPLE 执行器没有什么特别之处。REUSE 执行器重用预处理语句。BATCH 执行器重用语句和批量更新
    default-executor-type: REUSE
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    #设置超时时间，它决定驱动等待一个数据库响应的时间
    default-statement-timeout: 25000

#显示info
info:
  app.name: atguigu-microservicecloud
  company.name: www.cqut.li.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8081
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/young2?useUnicode=true&characterEncoding=utf8 #不需要\作为转移字符              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

  eureka:
    client: #客户端注册进eureka服务列表内
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: dept-8081.com
      prefer-ip-address: true     #访问路径可以显示IP地址
  mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.cqut.li.springcloud.entity  # 注意：对应实体类的路径
    configuration:
      #这个配置使全局的映射器启用或禁用缓存
      cache-enabled: true
      #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
      multiple-result-sets-enabled: true
      #配置默认的执行器。SIMPLE 执行器没有什么特别之处。REUSE 执行器重用预处理语句。BATCH 执行器重用语句和批量更新
      default-executor-type: REUSE
      #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
      lazy-loading-enabled: false
      aggressive-lazy-loading: true
      #设置超时时间，它决定驱动等待一个数据库响应的时间
      default-statement-timeout: 25000

  #显示info
  info:
    app.name: atguigu-microservicecloud
    company.name: www.cqut.li.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$